### ISSUE TITLE
Does PostgreSQL multitenant application?

### ISSUE THREAD

**Issue by ukumar29** [cap-js/cds-dbs#855] opened 2024-10-21 08:20 UTC
### Description of Scenario 

We wanted to develop multitenant application using node with PostgreSQL. Does PostgreSQL support Multitenancy, if yes then can you please share some reference doc to implement it.

Can we use [cds-js/postgres](https://www.npmjs.com/package/@cap-js/postgres) to implement multitenancy. As I could able to implement single tenant application with cds-js/postgres following [cap-doc](https://cap.cloud.sap/docs/guides/databases-postgres) .

Thanks in advance for your help.

**Comment by hakimio** [comment] 2024-10-21 08:50
It's stated in the docs that multitenancy is not supported:
https://cap.cloud.sap/docs/guides/databases-postgres#mtx-support

**Comment by BobdenOs** [comment] 2024-10-23 11:21
@ukumar29 I will close this issue as it is an duplicate of https://github.com/cap-js/cds-dbs/issues/400

**Closed by BobdenOs** 2024-10-23 11:21 UTC
Labels: bug
